---
title: "Workshop_1_Metropolis_Hastings"
author: "qvns53"
date: "2024-11-08"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
a_tune <- 3.8774367
N_iter <-  100000
```

```{r}
norm <- function(N,a) {
  vec <- rep(0, N)
  theta <- 0
  count <- 0 # to count acceptances for overall acceptance rate
  vec[1] <- theta
  
  for (i in 2:N) {
    innov <- runif(1, -a, a)   ## uniform U(-a, a) innovations
    candidate <- theta + innov
    laprob <- dnorm(candidate, log = TRUE) - dnorm(theta, log = TRUE)
    u <- runif(1)
    if (log(u) < laprob) { 
      theta <- candidate
      count <- count + 1
      }
    vec[i] <- theta
  }
  
  overall_acceptance_rate <- count/(N - 1)
  print(overall_acceptance_rate)
  return(vec)
  }

#Run for 10k iters with a=1:

normvec <- norm(N_iter, a_tune)   # N = 10,000 , a = 1

par(mfrow = c(2, 1))

plot(ts(normvec),
     ylab = "Value", xlab = "Iteration",
     main = "Trace plot")

histogram <- hist(normvec, freq = F,
     xlab = "Value", 
     main = "Histogram")

par(mfrow = c(1, 1))

norm_x <- seq(-4, 4, by = 0.01)
norm_y <- dnorm(norm_x)

lines(norm_x, norm_y)
```
